---
# - name: criando maquinas virtuais
#   hosts: hypervisor
#   become: true
#   vars_files:
#     - vms.yml

#   tasks:
- name: get VM disks
  command: "ls {{ vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"
  become: yes

- name: create disk
  command: >
            virt-builder 
            --format qcow2 {{ item.value.os_type_disk }}
            -o {{ vm_location}}/{{ item.key }}.{{ item.value.file_type }}
            --root-password password:{{ root_pass }}
  when: item.key not in disks.stdout
  with_dict: "{{ guests }}"
  become: yes

- name: get list of VMs
  virt:
    command: "list_vms"
  register: vms
  become: yes

- name: create vm
  command: >
            virt-install 
            --import 
            --name {{ item.key }}
            --memory {{ item.value.mem }} 
            --vcpus {{ item.value.cpus }}
            --disk {{ vm_location }}/{{ item.key }}.{{ item.value.file_type }}
            --noautoconsole 
            --os-variant {{ item.value.os_type }}
           
            --network  type=direct,source=enp6s0,source.mode=bridge,mac={{item.value.macadress}},model=virtio
            --autostart
  when: item.key not in vms.list_vms
  with_dict: "{{ guests }}"
  become: yes

- name: start vm
  virt:
    name: "{{ item.key }}"
    state: running
  with_dict: "{{ guests }}"
  become: yes