---
- name: 'Instala repositorios necessários'
  dnf:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-32.noarch.rpm
    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-32.noarch.rpm
    
- name: Atualizar tdos os pacotes
  dnf:
    name: "*"
    state: latest
  become: yes