- name: 'Instala drivers da placa de video'
  dnf:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - xorg-x11-drv-nvidia-390xx
    - akmod-nvidia-390xx

- name: Aplicando novas regras de firewall
  firewalld:
    port: 2222/tcp
    permanent: yes
    state: enabled
  become: yes
- name: Reiniciando a maquina após alterações
  reboot:
  become: yes