---
- name: Criar diretório {{ vm_location }}
  file:
    path: "{{ vm_location }}"
    state: directory
    mode: '0755'
  become: yes

- name: lista de  discos das vms
  command: "ls {{ vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"
  become: yes

            #--run-command 'useradd -m -G "wheel" "{{vm_user_group_name}}"'
            #--ssh-inject {{vm_user_group_name}}:file:/home/leandro/.ssh/id_rsa.pub
- name: Criando as maquinas virtuais 
  command: >
            virt-builder 
            --format qcow2 {{ item.value.os_type_disk }}
            -o {{ vm_location}}/{{ item.key }}.{{ item.value.file_type }}
            --root-password password:{{ vm_root_pass }}           
  when: item.key not in disks.stdout
  with_dict: "{{ guests }}"
  become: yes

- name: Lista de vms
  virt:
    command: "list_vms"
  register: vms
  become: yes  


- name: Instalando maquinas virtuais
  command: >
            virt-install 
            --import 
            --name {{ item.key }}
            --memory {{ item.value.mem }} 
            --vcpus {{ item.value.cpus }}
            --disk {{ vm_location }}/{{ item.key }}.{{ item.value.file_type }}             
            --os-variant {{ item.value.os_type }}           
            --network  type=direct,source=enp6s0,source.mode=bridge,mac={{item.value.macadress}},model=virtio
            --autostart
            --noautoconsole
  when: item.key not in vms.list_vms
  with_dict: "{{ guests }}"
  become: yes

# - name: Iniciando maquinas virtuais
#   virt:
#     name: "{{ item.key }}"
#     state: running
#   with_dict: "{{ guests }}"
#   become: yes